# Generated by Django 4.2.21 on 2025-05-13 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_like_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message',
            new_name='content',
        ),
    ]
